### ISSUE TITLE
Error after updating to 4x

### ISSUE THREAD

**Issue by spin-drift** [rajnandan1/kener#651]
Updating from Kener 3.2.14 to latest gives me the following error in Docker console:

```
[dotenv@17.2.4] injecting env (0) from .env -- tip: 🔑 add access controls to secrets: https://dotenvx.com/ops
[dotenv@17.2.4] injecting env (0) from .env -- tip: 🔄 add secrets lifecycle management: https://dotenvx.com/ops
[dotenv@17.2.4] injecting env (0) from .env -- tip: 🔐 encrypt with Dotenvx: https://dotenvx.com
[dotenv@17.2.4] injecting env (0) from .env -- tip: 🔐 encrypt with Dotenvx: https://dotenvx.com
[dotenv@17.2.4] injecting env (0) from .env -- tip: 👥 sync secrets across teammates & machines: https://dotenvx.com/ops
[dotenv@17.2.4] injecting env (0) from .env -- tip: ⚙️  enable debug logging with { debug: true }
file:///app/build/main.js:7968
var localeModules = import.meta.glob("/src/lib/locales/*.json", {
                                ^

TypeError: (intermediate value).glob is not a function
    at file:///app/build/main.js:7968:33
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
```
